<a href="https://colab.research.google.com/github/Aayushee07/AdsLabs/blob/main/Aayushi_ads_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ADS lab 2**

Dataset : Crop Production in India ([Link](https://www.kaggle.com/datasets/abhinand05/crop-production-in-india))

This dataset provides a huge amount of information on crop production in India ranging from several years. It's a state-wise Indian crop production dataset.

Features

**State_Name**: The name of the state or region where the crop was cultivated.
**District_Name**: The name of the district within the state where the crop was cultivated.
**Crop_Year**: The year in which the crop was cultivated.
**Season**: The season during which the crop was cultivated (e.g., Kharif, Rabi, Whole Year).
**Crop**: The name or type of crop that was cultivated.
**Area**: The land area (in hectares or acres) on which the crop was cultivated.
**Production**: The quantity of crop produced (in metric tons or other relevant units).

In [ ]:
import pandas as pd
df = pd.read_csv('crop_production.csv')
df

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
246087,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
246088,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
246089,West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
246090,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

In [ ]:
df.describe()

           Crop_Year          Area    Production
count  246091.000000  2.460910e+05  2.423610e+05
mean     2005.643018  1.200282e+04  5.825034e+05
std         4.952164  5.052340e+04  1.706581e+07
min      1997.000000  4.000000e-02  0.000000e+00
25%      2002.000000  8.000000e+01  8.800000e+01
50%      2006.000000  5.820000e+02  7.290000e+02
75%      2010.000000  4.392000e+03  7.023000e+03
max      2015.000000  8.580100e+06  1.250800e+09

In [ ]:
df.mean()

<ipython-input-11-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

Crop_Year       2005.643018
Area           12002.820864
Production    582503.442251
dtype: float64

In [ ]:
df.median()

<ipython-input-12-6d467abf240d>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()

Crop_Year     2006.0
Area           582.0
Production     729.0
dtype: float64

In [ ]:
df.mode()

      State_Name District_Name  Crop_Year       Season  Crop  Area  Production
0  Uttar Pradesh       BIJAPUR       2003  Kharif       Rice   1.0         1.0

In [ ]:
#mean>median>mode so positively skewed (consists of outliers)

In [ ]:
missing_values = df.isnull().sum()
print(missing_values)

State_Name          0
District_Name       0
Crop_Year           0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64

In [ ]:
# 1. Fill missing values with the maximum value in the column
df_max = df.fillna(df.max())

print("\nCleaned Dataset - Max Value:")
print(df_max.head())

Cleaned Dataset - Max Value:
                    State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year

                  Crop    Area  Production
0             Arecanut  1254.0      2000.0
1  Other Kharif pulses     2.0         1.0
2                 Rice   102.0       321.0
3               Banana   176.0       641.0
4            Cashewnut   720.0       165.0

In [ ]:
missing_values = df_max.isnull().sum()
print(missing_values)

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [ ]:
# 2. Fill missing values with the minimum value in the column
df_min = df.fillna(df.min())

print("\nCleaned Dataset - Min Value:")
print(df_min.head())

Cleaned Dataset - Min Value:
                    State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year

                  Crop    Area  Production
0             Arecanut  1254.0      2000.0
1  Other Kharif pulses     2.0         1.0
2                 Rice   102.0       321.0
3               Banana   176.0       641.0
4            Cashewnut   720.0       165.0

In [ ]:
missing_values = df_min.isnull().sum()
print(missing_values)

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [ ]:
drop_column = ["State_Name","District_Name","Season","Crop"]
df_drop = df.drop(columns = drop_column)
df_drop

        Crop_Year      Area  Production
0            2000    1254.0      2000.0
1            2000       2.0         1.0
2            2000     102.0       321.0
3            2000     176.0       641.0
4            2000     720.0       165.0
...           ...       ...         ...
246086       2014     306.0       801.0
246087       2014     627.0       463.0
246088       2014     324.0     16250.0
246089       2014  279151.0    597899.0
246090       2014     175.0        88.0

[246091 rows x 3 columns]

In [ ]:
# 3. Fill missing values using k-means clustering
from sklearn.impute import KNNImputer
knn_imputer = KNNImputer(n_neighbors=2)
df_kmeans = pd.DataFrame(data=knn_imputer.fit_transform(df_drop), columns=df_drop.columns)
print("\nCleaned Dataset - K-means:")
print(df_kmeans.head())

Cleaned Dataset - K-means:
   Crop_Year    Area  Production
0     2000.0  1254.0      2000.0
1     2000.0     2.0         1.0
2     2000.0   102.0       321.0
3     2000.0   176.0       641.0
4     2000.0   720.0       165.0

In [ ]:
missing_values = df_kmeans.isnull().sum()
print(missing_values)

Crop_Year     0
Area          0
Production    0
dtype: int64

In [ ]:
# 4. Fill missing values with a fixed value
df_fixed_value = df.fillna(0)

print("\nCleaned Dataset - Fixed Value:")
print(df_fixed_value.head())

Cleaned Dataset - Fixed Value:
                    State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year

                  Crop    Area  Production
0             Arecanut  1254.0      2000.0
1  Other Kharif pulses     2.0         1.0
2                 Rice   102.0       321.0
3               Banana   176.0       641.0
4            Cashewnut   720.0       165.0

In [ ]:
missing_values = df_fixed_value.isnull().sum()
print(missing_values)

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [ ]:
# 5. Fill missing values with the most frequent value in the column
df_most_frequent = df.apply(lambda x: x.fillna(x.value_counts().index[0]))

print("\nCleaned Dataset - Most Frequent Value:")
print(df_most_frequent.head())

Cleaned Dataset - Most Frequent Value:
                    State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year

                  Crop    Area  Production
0             Arecanut  1254.0      2000.0
1  Other Kharif pulses     2.0         1.0
2                 Rice   102.0       321.0
3               Banana   176.0       641.0
4            Cashewnut   720.0       165.0

In [ ]:
missing_values = df_most_frequent.isnull().sum()
print(missing_values)

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [ ]:
# 6. Fill missing values using linear interpolation
df_interpolated = df.interpolate()

# Display cleaned datasets
print("\nCleaned Dataset - Interpolated:")
print(df_interpolated.head())

Cleaned Dataset - Interpolated:
                    State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year

                  Crop    Area  Production
0             Arecanut  1254.0      2000.0
1  Other Kharif pulses     2.0         1.0
2                 Rice   102.0       321.0
3               Banana   176.0       641.0
4            Cashewnut   720.0       165.0

In [ ]:
missing_values = df_interpolated.isnull().sum()
print(missing_values)

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [ ]:
# Impute missing values in 'Production' column with median as there are outliers
median_production = df['Production'].median()
df['Production'].fillna(median_production, inplace=True)
df

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
246087,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
246088,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
246089,West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
246090,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

In [ ]:
missing_values = df.isnull().sum()
print(missing_values)

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [ ]:
# Check for duplicate rows
duplicate_rows = df[df.duplicated()]

# Display duplicate rows, if any
if not duplicate_rows.empty:
    print("Duplicate Rows:")
    print(duplicate_rows)
else:
    print("No duplicate rows found.")

No duplicate rows found.

In [ ]:
# Standardize text data
df['State_Name'] = df['State_Name'].str.lower()
df['District_Name'] = df['District_Name'].str.lower()
df['Season'] = df['Season'].str.strip().str.lower()
df['Crop'] = df['Crop'].str.strip().str.lower()

In [ ]:
# Check consistency in categorical variables
print("Unique Seasons:", df['Season'].unique())
print("Unique Crops:", df['Crop'].unique())

Unique Seasons: ['kharif' 'whole year' 'autumn' 'rabi' 'summer' 'winter']
Unique Crops: ['arecanut' 'other kharif pulses' 'rice' 'banana' 'cashewnut' 'coconut'
 'dry ginger' 'sugarcane' 'sweet potato' 'tapioca' 'black pepper'
 'dry chillies' 'other oilseeds' 'turmeric' 'maize' 'moong(green gram)'
 'urad' 'arhar/tur' 'groundnut' 'sunflower' 'bajra' 'castor seed'
 'cotton(lint)' 'horse-gram' 'jowar' 'korra' 'ragi' 'tobacco' 'gram'
 'wheat' 'masoor' 'sesamum' 'linseed' 'safflower' 'onion'
 'other misc. pulses' 'samai' 'small millets' 'coriander' 'potato'
 'other  rabi pulses' 'soyabean' 'beans & mutter(vegetable)' 'bhindi'
 'brinjal' 'citrus fruit' 'cucumber' 'grapes' 'mango' 'orange'
 'other fibres' 'other fresh fruits' 'other vegetables' 'papaya'
 'pome fruit' 'tomato' 'rapeseed &mustard' 'mesta' 'cowpea(lobia)' 'lemon'
 'pome granet' 'sapota' 'cabbage' 'peas  (vegetable)' 'niger seed'
 'bottle gourd' 'sannhamp' 'varagu' 'garlic' 'ginger' 'oilseeds total'
 'pulses total' 'jute' 'peas & beans (pulses)' 'blackgram' 'paddy'
 'pineapple' 'barley' 'khesari' 'guar seed' 'moth'
 'other cereals & millets' 'cond-spcs other' 'turnip' 'carrot' 'redish'
 'arcanut (processed)' 'atcanut (raw)' 'cashewnut processed'
 'cashewnut raw' 'cardamom' 'rubber' 'bitter gourd' 'drum stick'
 'jack fruit' 'snak guard' 'pump kin' 'tea' 'coffee' 'cauliflower'
 'other citrus fruit' 'water melon' 'total foodgrain' 'kapas' 'colocosia'
 'lentil' 'bean' 'jobster' 'perilla' 'rajmash kholar' 'ricebean (nagadal)'
 'ash gourd' 'beet root' 'lab-lab' 'ribed guard' 'yam' 'apple' 'peach'
 'pear' 'plums' 'litchi' 'ber' 'other dry fruit' 'jute & mesta']

In [ ]:

# 'Area' should be non-negative, and 'Production' should be non-negative and within a reasonable upper limit
reasonable_area_range = (0, float('inf'))  # Area should be non-negative
reasonable_production_range = (0, 100000)  # Production should be non-negative and less than 100,000 (example upper limit)

# Perform data validation for 'Area'
invalid_area_values = df[(df['Area'] < reasonable_area_range[0]) | (df['Area'] > reasonable_area_range[1])]
if not invalid_area_values.empty:
    print("Invalid 'Area' values found:")
    print(invalid_area_values)

# Perform data validation for 'Production'
invalid_production_values = df[(df['Production'] < reasonable_production_range[0]) | (df['Production'] > reasonable_production_range[1])]
if not invalid_production_values.empty:
    print("Invalid 'Production' values found:")
    print(invalid_production_values)

Invalid 'Production' values found:
                         State_Name District_Name  Crop_Year      Season  \
5       andaman and nicobar islands      nicobars       2000  whole year
14      andaman and nicobar islands      nicobars       2001  whole year
23      andaman and nicobar islands      nicobars       2002  whole year
32      andaman and nicobar islands      nicobars       2003  whole year
41      andaman and nicobar islands      nicobars       2004  whole year
...                             ...           ...        ...         ...
245954                  west bengal       purulia       2010      winter
245985                  west bengal       purulia       2011      winter
246017                  west bengal       purulia       2012      winter
246052                  west bengal       purulia       2013      winter
246089                  west bengal       purulia       2014      winter

           Crop       Area  Production
5       coconut   18168.00  65100000.0
14      coconut   18190.00  64430000.0
23      coconut   18240.00  67490000.0
32      coconut   18284.74  68580000.0
41      coconut   18394.70  52380000.0
...         ...        ...         ...
245954     rice  152676.00    261435.0
245985     rice  270270.00    731799.0
246017     rice  288735.00    729553.0
246052     rice  302274.00    730136.0
246089     rice  279151.00    597899.0

[18208 rows x 7 columns]

In [ ]:
import pandas as pd
from scipy import stats

#z-scores for 'Area' and 'Production' columns
z_scores_area = stats.zscore(df['Area'])
z_scores_production = stats.zscore(df['Production'])

# Define threshold for outlier detection (e.g., z-score > 3 or < -3)
threshold = 3

# Identify outliers based on threshold
outliers_area = df[abs(z_scores_area) > threshold]
outliers_production = df[abs(z_scores_production) > threshold]

# Remove outliers
cleaned_df = df[(abs(z_scores_area) <= threshold) & (abs(z_scores_production) <= threshold)]

# Display summary after outlier removal
print("Summary after outlier removal:")
print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", cleaned_df.shape)

Summary after outlier removal:
Original dataset shape: (246091, 7)
Cleaned dataset shape: (242208, 7)

In [ ]:
print(cleaned_df)
cleaned_df.to_csv('cleaned_data.csv', index=False)

                         State_Name District_Name  Crop_Year      Season  \
0       andaman and nicobar islands      nicobars       2000      kharif
1       andaman and nicobar islands      nicobars       2000      kharif
2       andaman and nicobar islands      nicobars       2000      kharif
3       andaman and nicobar islands      nicobars       2000  whole year
4       andaman and nicobar islands      nicobars       2000  whole year
...                             ...           ...        ...         ...
246085                  west bengal       purulia       2014      summer
246086                  west bengal       purulia       2014      summer
246087                  west bengal       purulia       2014      summer
246088                  west bengal       purulia       2014  whole year
246090                  west bengal       purulia       2014      winter

                       Crop    Area  Production
0                  arecanut  1254.0      2000.0
1       other kharif pulses     2.0         1.0
2                      rice   102.0       321.0
3                    banana   176.0       641.0
4                 cashewnut   720.0       165.0
...                     ...     ...         ...
246085                maize   325.0      2039.0
246086                 rice   306.0       801.0
246087              sesamum   627.0       463.0
246088            sugarcane   324.0     16250.0
246090              sesamum   175.0        88.0

[242208 rows x 7 columns]